version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"

  database:
    build:
      context: ./database
    ports:
      - "3306:3306"
    environment: MYSQL_ROOT_PASSWORD:root MYSQL_DATABASE:mydatabase MYSQL_USER:root MYSQL_PASSWORD:root

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
