# Generated by Django 4.2.6 on 2023-10-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_name_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='number_cars',
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='user.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.company')),
            ],
        ),
    ]
