# Generated by Django 4.2.6 on 2023-10-23 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_company_number_cars_alter_company_user_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('min_latitude', models.FloatField()),
                ('max_longitude', models.FloatField()),
                ('min_accelaration', models.FloatField()),
                ('max_accelaration', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='user.company')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('acceleration', models.FloatField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='user.car')),
            ],
        ),
    ]
