# Generated by Django 4.2.6 on 2023-10-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_standard_max_latitude_standard_min_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='max_accelaration',
            new_name='max_acceleration',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='min_accelaration',
            new_name='min_acceleration',
        ),
    ]
