# Generated by Django 4.2.6 on 2023-10-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_wrongecars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WrongeCars',
            new_name='NonStandardCars',
        ),
    ]
