# Generated by Django 4.2.6 on 2023-10-31 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_wrongecars_nonstandardcars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NonStandardCars',
            new_name='Messages',
        ),
    ]
