# Generated by Django 4.2.6 on 2023-11-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_standard_company_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user.car'),
        ),
    ]
